# Generated by Django 5.2.4 on 2025-11-26 06:02

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, validators=[movies.models.validate]),
        ),
    ]
